name: Flutter Nightly Build on push and pull

on:
  push:
    branches: master
  pull_request_target:
    branches: master
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true

